runtime: go115
env: standard
entrypoint: 
instance_class: F2

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: 3000ms
  min_instances: 0
  max_instances: 1

handlers:
  - url: /$
    static_files: dist/index.html
    upload: dist/index.html
  - url: /(.+\.(html|css|js|gif|png|jpg))$
    static_files: dist/\1
    upload: public/.+\.(html|css|js|gif|png|jpg)$
  - url: /.*
    script: auto