runtime: php55
env: standard
instance_class: F2

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: 3000ms
  min_instances: 0
  max_instances: 1

handlers:
- url: /(.*\.(json|ico|js|css|png|jpg|gif|woff|woff2|map))$
  static_files: dist/\1
  upload: dist/(.*)(\.(json|ico|js|css|png|jpg|gif|woff|woff2|map))$
  secure: always

- url: /.*
  static_files: dist/index.html
  upload: dist/index.html
  secure: always
